"use client";
import ImageCompressor from "@/components/special/ImageCompressor";
import ImageResizer from "@/components/special/ImageResizer";
import ImageFormatConverter from "@/components/special/ImageFormatConverter";
import ImageCropper from "@/components/special/ImageCropper";
import ImageToPdf from "@/components/special/ImageToPdf";
import MergePdf from "@/components/special/MergePdf";
import SplitPdf from "@/components/special/SplitPdf";
import JsonFormatter from "@/components/special/JsonFormatter";
import Base64Encoder from "@/components/special/Base64Encoder";
import Base64Decoder from "@/components/special/Base64Decoder";
import UrlEncoder from "@/components/special/UrlEncoder";
import UrlDecoder from "@/components/special/UrlDecoder";
import UuidGenerator from "@/components/special/UuidGenerator";
import SlugGenerator from "@/components/special/SlugGenerator";
import RemoveLineBreaks from "@/components/special/RemoveLineBreaks";
import TextSorter from "@/components/special/TextSorter";
import DuplicateLineRemover from "@/components/special/DuplicateLineRemover";
import TextReverser from "@/components/special/TextReverser";
import RemoveExtraSpaces from "@/components/special/RemoveExtraSpaces";
import LineCounter from "@/components/special/LineCounter";
import WordFrequencyCounter from "@/components/special/WordFrequencyCounter";
import TextRepeater from "@/components/special/TextRepeater";
import TextToBinary from "@/components/special/TextToBinary";
import BinaryToText from "@/components/special/BinaryToText";
import RgbToHex from "@/components/special/RgbToHex";
import HexToRgb from "@/components/special/HexToRgb";
import UnixTimestampConverter from "@/components/special/UnixTimestampConverter";
import RandomLetterGenerator from "@/components/special/RandomLetterGenerator";
import PasswordStrengthChecker from "@/components/special/PasswordStrengthChecker";
import UuidBulkGenerator from "@/components/special/UuidBulkGenerator";
import MetaDescriptionCounter from "@/components/special/MetaDescriptionCounter";
import HtmlEscape from "@/components/special/HtmlEscape";
import HtmlUnescape from "@/components/special/HtmlUnescape";
import ListRandomizer from "@/components/special/ListRandomizer";
import RomanNumeralConverter from "@/components/special/RomanNumeralConverter";

export default function SpecialToolRenderer({ slug }: { slug: string }) {
  if (slug === "compress-image") return <ImageCompressor />;
  if (slug === "resize-image") return <ImageResizer />;
  if (slug === "jpg-to-png") return <ImageFormatConverter mime="image/png" />;
  if (slug === "png-to-jpg") return <ImageFormatConverter mime="image/jpeg" />;
  if (slug === "crop-image") return <ImageCropper />;
  if (slug === "image-to-pdf") return <ImageToPdf />;
  if (slug === "merge-pdf") return <MergePdf />;
  if (slug === "split-pdf") return <SplitPdf />;
  if (slug === "json-formatter") return <JsonFormatter />;
  if (slug === "base64-encoder") return <Base64Encoder />;
  if (slug === "base64-decoder") return <Base64Decoder />;
  if (slug === "url-encoder") return <UrlEncoder />;
  if (slug === "url-decoder") return <UrlDecoder />;
  if (slug === "uuid-generator") return <UuidGenerator />;
  if (slug === "slug-generator") return <SlugGenerator />;
  if (slug === "remove-line-breaks") return <RemoveLineBreaks />;
  if (slug === "text-sorter") return <TextSorter />;
  if (slug === "duplicate-line-remover") return <DuplicateLineRemover />;
  if (slug === "png-compressor") return <ImageCompressor />;
  if (slug === "webp-to-png") return <ImageFormatConverter mime="image/png" />;
  if (slug === "text-reverser") return <TextReverser />;
  if (slug === "remove-extra-spaces") return <RemoveExtraSpaces />;
  if (slug === "line-counter") return <LineCounter />;
  if (slug === "word-frequency-counter") return <WordFrequencyCounter />;
  if (slug === "text-repeater") return <TextRepeater />;
  if (slug === "text-to-binary") return <TextToBinary />;
  if (slug === "binary-to-text") return <BinaryToText />;
  if (slug === "rgb-to-hex") return <RgbToHex />;
  if (slug === "hex-to-rgb") return <HexToRgb />;
  if (slug === "unix-timestamp-converter") return <UnixTimestampConverter />;
  if (slug === "random-letter-generator") return <RandomLetterGenerator />;
  if (slug === "password-strength-checker") return <PasswordStrengthChecker />;
  if (slug === "uuid-bulk-generator") return <UuidBulkGenerator />;
  if (slug === "meta-description-counter") return <MetaDescriptionCounter />;
  if (slug === "html-escape") return <HtmlEscape />;
  if (slug === "html-unescape") return <HtmlUnescape />;
  if (slug === "list-randomizer") return <ListRandomizer />;
  if (slug === "roman-numeral-converter") return <RomanNumeralConverter />;
  return null;
}
