export type ProgrammaticPage = {
  slug: string;
  title: string;
  description: string;
  category: string;
  relatedTool: string;
  parentLanding: string;
};

export const programmaticPages: ProgrammaticPage[] = [
  {
    slug: "jpg-to-png-online",
    title: "JPG to PNG Online",
    description: "Convert JPG to PNG online in your browser without installing extra software.",
    category: "Image",
    relatedTool: "jpg-to-png",
    parentLanding: "/image-tools",
  },
  {
    slug: "png-to-jpg-online",
    title: "PNG to JPG Online",
    description: "Convert PNG to JPG online for uploads, email, and websites.",
    category: "Image",
    relatedTool: "png-to-jpg",
    parentLanding: "/image-tools",
  },
  {
    slug: "compress-image-for-email",
    title: "Compress Image for Email",
    description: "Reduce image size before sending files by email.",
    category: "Image",
    relatedTool: "compress-image",
    parentLanding: "/image-tools",
  },
  {
    slug: "compress-image-for-website",
    title: "Compress Image for Website",
    description: "Shrink image size for faster pages and cleaner uploads.",
    category: "Image",
    relatedTool: "compress-image",
    parentLanding: "/image-tools",
  },
  {
    slug: "merge-pdf-online",
    title: "Merge PDF Online",
    description: "Combine PDF files online in a simple browser-based workflow.",
    category: "PDF",
    relatedTool: "merge-pdf",
    parentLanding: "/pdf-tools",
  },
  {
    slug: "split-pdf-online",
    title: "Split PDF Online",
    description: "Extract selected pages from a PDF online.",
    category: "PDF",
    relatedTool: "split-pdf",
    parentLanding: "/pdf-tools",
  },
  {
    slug: "loan-calculator-monthly-payment",
    title: "Loan Calculator Monthly Payment",
    description: "Estimate monthly loan payments using a simple online calculator.",
    category: "Finance",
    relatedTool: "loan-calculator",
    parentLanding: "/online-calculators",
  },
  {
    slug: "mortgage-calculator-payment",
    title: "Mortgage Calculator Payment",
    description: "Estimate mortgage payment amounts before you apply.",
    category: "Finance",
    relatedTool: "mortgage-calculator",
    parentLanding: "/online-calculators",
  },
  {
    slug: "bmi-calculator-for-men",
    title: "BMI Calculator for Men",
    description: "Estimate BMI quickly with a simple BMI calculator for men.",
    category: "Health",
    relatedTool: "bmi-calculator",
    parentLanding: "/online-calculators",
  },
  {
    slug: "bmi-calculator-for-women",
    title: "BMI Calculator for Women",
    description: "Estimate BMI quickly with a simple BMI calculator for women.",
    category: "Health",
    relatedTool: "bmi-calculator",
    parentLanding: "/online-calculators",
  },
  {
    slug: "tip-calculator-by-bill-amount",
    title: "Tip Calculator by Bill Amount",
    description: "Calculate tip and total by bill amount in a few seconds.",
    category: "Utility",
    relatedTool: "tip-calculator",
    parentLanding: "/free-tools",
  },
  {
    slug: "percentage-calculator-online",
    title: "Percentage Calculator Online",
    description: "Solve percentage questions online without doing the math by hand.",
    category: "Utility",
    relatedTool: "percentage-calculator",
    parentLanding: "/free-tools",
  },
  {
  slug: "json-formatter-online",
  title: "JSON Formatter Online",
  description: "Format and beautify JSON online in your browser.",
  category: "Utility",
  relatedTool: "json-formatter",
  parentLanding: "/free-tools",
},
{
  slug: "base64-encoder-online",
  title: "Base64 Encoder Online",
  description: "Encode text to Base64 online instantly.",
  category: "Utility",
  relatedTool: "base64-encoder",
  parentLanding: "/free-tools",
},
{
  slug: "base64-decoder-online",
  title: "Base64 Decoder Online",
  description: "Decode Base64 text online instantly.",
  category: "Utility",
  relatedTool: "base64-decoder",
  parentLanding: "/free-tools",
},
{
  slug: "url-encoder-online",
  title: "URL Encoder Online",
  description: "Encode text for URL use online.",
  category: "Utility",
  relatedTool: "url-encoder",
  parentLanding: "/free-tools",
},
{
  slug: "url-decoder-online",
  title: "URL Decoder Online",
  description: "Decode URL text online instantly.",
  category: "Utility",
  relatedTool: "url-decoder",
  parentLanding: "/free-tools",
},
{
  slug: "uuid-generator-online",
  title: "UUID Generator Online",
  description: "Generate UUIDs online in your browser.",
  category: "Utility",
  relatedTool: "uuid-generator",
  parentLanding: "/free-tools",
},
{
  slug: "slug-generator-online",
  title: "Slug Generator Online",
  description: "Generate clean URL slugs from text online.",
  category: "Writing",
  relatedTool: "slug-generator",
  parentLanding: "/free-tools",
},
{
  slug: "remove-line-breaks-online",
  title: "Remove Line Breaks Online",
  description: "Remove line breaks from text online.",
  category: "Writing",
  relatedTool: "remove-line-breaks",
  parentLanding: "/free-tools",
},
{
  slug: "text-sorter-online",
  title: "Text Sorter Online",
  description: "Sort lines of text alphabetically online.",
  category: "Writing",
  relatedTool: "text-sorter",
  parentLanding: "/free-tools",
},
{
  slug: "duplicate-line-remover-online",
  title: "Duplicate Line Remover Online",
  description: "Remove duplicate lines from text online.",
  category: "Writing",
  relatedTool: "duplicate-line-remover",
  parentLanding: "/free-tools",
},
];
